### PR TITLE
feat: while switching between dark/light add splash effect

### PR DESCRIPTION
**Pull request by rsmelo92**
Because

- while switching to dark/light mode need to add some css effects

This commit

- adds a quick implementation using tailwind + javascript

https://github.com/instill-ai/instill.tech/assets/16295402/c3bafeae-bed0-4925-9242-21c833cf89ad

### CODE REVIEW

**Comment by iamnamananand996** [comment]
Hi @rsmelo92, 
I checked the PR the implementation looks bit `hacky`.
css transition does not help. 😬

**Comment by rsmelo92** [comment]
hello @iamnamananand996 I do agree, the removal of the `transition` is a bit hacky, do you have any suggestion? Looking at the codebase its the least intrusive way that I thought of doing it 🙃

**Comment by rsmelo92** [comment]
one more thing, Vue docs that was used in the example uses css-transition
The "hacky" way that I did was to make sure that we don't keep the transition after we change to darkmode, but they didnt care about that and just kept the transition always, I could change to same behavior if that's better

https://github.com/instill-ai/instill.tech/assets/16295402/d0d5d5a6-914d-4df1-86ee-11f6aec00ded

**Comment by EiffelFly** [comment]
Closed due to the ambiguity of implementation scope

**Pull request closed without merging**
