### PR TITLE
fix: added mouse hover dropdown effect

### PR DESCRIPTION
**Pull request by anurag629**
Because

- Now, Dropdown open onHover mouse event

### CODE REVIEW

**Comment by anurag629** [comment]
Fixes instill-ai/instill.tech:#416

**Comment by anurag629** [comment]
Fixes instill-ai/community#416

**Comment by iamnamananand996** [comment]
Hi @anurag629, Thanks for contributing to our repository. 

I have check the above changes, and found the dropdown open `onHover` but didn't close when mouse is remove from the dropdown component.
Have a look :-

 
https://github.com/instill-ai/instill.tech/assets/31537362/28b74b40-efa9-4616-bc29-6e4c43951d87

**Comment by anurag629** [comment]
> Hi @anurag629. We appreciate your contribution.
> 
> But if there is no following update, we will close this PR. As always, look forward to seeing you here again

@EiffelFly, I was busy last week, I'll commit changes by tomorrow.

**Comment by EiffelFly** [comment]
Closed due to lack of activity

**Pull request closed without merging**
