### PR TITLE
fix: sitemap path fix (#538)

### PR DESCRIPTION
**Pull request by iamnamananand996**
Because

- video.xml is not correctly generated

This commit

- correct path to generated videos sitemap

### CODE REVIEW

**Comment by iamnamananand996** [comment]
Hi @EiffelFly ,
the current implementation has been changes to static sitemap generation for `videos` also.

Now all the sitemap are generated in a single file.
working example
[https://www.instill-inc.tech/sitemap-0.xml](https://www.instill-inc.tech/sitemap-0.xml)

**Comment by EiffelFly** [comment]
@iamnamananand996 there are multiple issues here:

- Ideally the video sitemap should be generated into single file /videos.xml and don't mix with the sitemap-0.xml with other articles. Cloud you adjust your implementation about this?
- The changefreq should not be daily, monthly will be more appreiate.
- There is no need to write additional fetch function to get youtube meta, [get-markdown-video-meta](https://github.com/EiffelFly/get-markdown-video-meta) should already provide all the meta you need.

**Comment by iamnamananand996** [comment]
> @iamnamananand996 there are multiple issues here:
> 
> * Ideally the video sitemap should be generated into single file /videos.xml and don't mix with the sitemap-0.xml with other articles. Cloud you adjust your implementation about this?
> * The changefreq should not be daily, monthly will be more appreiate.
> * There is no need to write additional fetch function to get youtube meta, [get-markdown-video-meta](https://github.com/EiffelFly/get-markdown-video-meta) should already provide all the meta you need.

I was expecting these comment from your side.
regarding these **point 1 and point 3** are not supported, when we use static sitemap generation

- `/videos.xml is only possible when we do serverside-sitemap`
- I tried to added [get-markdown-video-meta](https://github.com/EiffelFly/get-markdown-video-meta), but the library was not able to import under `next-sitemap.config.js`

**Comment by EiffelFly** [comment]
@iamnamananand996 I had pushed code to address above issue

- Yes you are right, currently there has no way to static generate the sitemap like `videos.xml.tsx`
- I tried to added [get-markdown-video-meta](https://github.com/EiffelFly/get-markdown-video-meta), but the library was not able to import under next-sitemap.config.js. That is due to remark.js is a ESM only library. So I had changed the next-sitemap config to next-sitemap.config.mjs.
- The top-level changefreq will affect all the sitemap, but we only want to make video changefreq to monthly. Other can stay daily. (Please make sure every code you change don't have unexpected side-effect)

**Comment by iamnamananand996** [comment]
> @iamnamananand996 I had pushed code to address above issue
> 
> * Yes you are right, currently there has no way to static generate the sitemap like `videos.xml.tsx`
> * > I tried to added [get-markdown-video-meta](https://github.com/EiffelFly/get-markdown-video-meta), but the library was not able to import under next-sitemap.config.js.
>   
>   
>   
>   * That is due to remark.js is a ESM only library. So I had changed the next-sitemap config to next-sitemap.config.mjs.
> * The top-level changefreq will affect all the sitemap, but we only want to make video changefreq to monthly. Other can stay daily. (Please make sure every code you change don't have unexpected side-effect) (But this is also a oversight of me, don't worry)

Hi @EiffelFly 

I found a way for point 1, but it will be like create a new file manually and adding the sitemap for video their. this is not provided by library.

if we really need it, I can add that I will take some extra function to generate the file.

**Comment by EiffelFly** [comment]
@iamnamananand996 I think currently we can stick with this version, the function is stable and workable, let move to other task!

**Comment by iamnamananand996** [comment]
> @iamnamananand996 I think currently we can stick with this version, the function is stable and workable, let move to other task!

okay

**Review by EiffelFly — APPROVED** [review]
LGTM!

**Pull request merged**
